### ISSUE TITLE
can't load plugin with partial fix

### ISSUE THREAD

**Issue by supyrow** [devbisme/WireIt#17]
wanted to try the plugin and kept pulling an  error...  I got it to the point where the icons appear and working with the exception of saving.  also might just be my setup, however i cannot change the dimensions of the save window and cannot read the text, nor see the textbox, drag and drop does not appear to work.

![change](https://user-images.githubusercontent.com/25697854/115802483-faa8c900-a3ac-11eb-8526-c5e4c13678d8.png)
![dimensions](https://user-images.githubusercontent.com/25697854/115802484-faa8c900-a3ac-11eb-81fc-e9a2ac9cc13c.png)

Application: KiCad PCB Editor

Version: 5.99.0-unknown-9b1890606d~127~ubuntu20.04.1, release build

Libraries:
	wxWidgets 3.0.4
	libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3

Platform: Linux 5.4.0-73-generic x86_64, 64 bit, Little endian, wxGTK, KDE, x11

Build Info:
	Date: Apr 22 2021 08:36:31
	wxWidgets: 3.0.4 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.24
	Boost: 1.71.0
	OCC: 7.3.0
	Curl: 7.68.0
	ngspice: 31
	Compiler: GCC 9.3.0 with C++ ABI 1013

Build settings:
	KICAD_SCRIPTING=ON
	KICAD_SCRIPTING_MODULES=ON
	KICAD_SCRIPTING_PYTHON3=ON
	KICAD_SCRIPTING_WXPYTHON=ON
	KICAD_SCRIPTING_WXPYTHON_PHOENIX=ON
	KICAD_SCRIPTING_ACTION_MENU=ON
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON

**Comment by Plinsboorg** [comment]
https://github.com/devbisme/WireIt/pull/20
Hello, you can try changes from my pull request
