### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by MrM40** [devbisme/WireIt#7]
KiCad version 5.0.0
I don't have the "scripting\plugins" folder (I created in manually).
I don't have the Tools\External Plugins menu in Pcbnew?

What am I missing (I'm new to KiCad)?

**Comment by xesscorp** [comment]
The `kicad/share/kicad/scripting/plugins` directory applies to Windows. Under linux, it looks like it should be `kicad/scripting/plugins`.
